#spring.h2.console.enabled=true

# datasource setting
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop # H2 1.4.200 버전부터 MVCC(;MVCC=TRUE) 옵션이 제거되었다.
#    username : sa
#    password:
#    driver-class-name: org.h2.Driver
#

# Database setting
server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/gymzzak
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true

# JPA setting
jpa:
  properties:
    hibernate:
      hbm2ddl: validate # 현재 엔티티 매핑 정보와 DB 스키마가 같은지 비교하고 만약 다르면 경고를 남기고 실행 X
      show_sql: true # hibernate 가 DB 에 날리는 모든 쿼리를 보여준다. > sysout 으로 찍기 때문에 운영에선 사용 X
      format_sql : true # 보여지는 쿼리를 예쁘게 세팅한다.
      new_generator_mappings : true # JPA 에 맞춘 새로운 ID 생성 방법을 사용한다. 하이버네이트 레거시를 운영하는 것이 아니라면 항상 TRUE

# log level
logging:
  level:
    org.hibernate.SQL: debug # logger 를 통해 hibernate 실행 SQL 을 남긴다.
    org.hibernate.type: trace